version: "3.2"
services:
  monitor-worker:
    image: apseo-nexus:8083/qe/gatling-monitor-worker:latest
    network_mode: "host"
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=2003
      - LOG_LEVEL=INFO
    ports:
      - '8999:8999/udp'